export const FETCH_JOBS_START = 'FETCH_JOBS_START';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_FAIL = 'FETCH_JOBS_FAIL';
export const RE_SET_COUNT_JOBS_SUCCESS = 'RE_SET_COUNT_JOBS_SUCCESS';

export const FETCH_JOB_START = 'FETCH_JOB_START';
export const FETCH_JOB_SUCCESS = 'FETCH_JOB_SUCCESS';
export const FETCH_JOB_FAIL = 'FETCH_JOB_FAIL';

export const FETCH_RELATED_JOBS_IN_JOB_START = 'FETCH_RELATED_JOBS_IN_JOB_START';
export const FETCH_RELATED_JOBS_IN_JOB_SUCCESS = 'FETCH_RELATED_JOBS_IN_JOB_SUCCESS';
export const FETCH_RELATED_JOBS_IN_JOB_FAIL = 'FETCH_RELATED_JOBS_IN_JOB_FAIL';

export const FETCH_RELATED_SKILLS_IN_JOB_START = 'FETCH_RELATED_SKILLS_IN_JOB_START';
export const FETCH_RELATED_SKILLS_IN_JOB_SUCCESS = 'FETCH_RELATED_SKILLS_IN_JOB_SUCCESS';
export const FETCH_RELATED_SKILLS_IN_JOB_FAIL = 'FETCH_RELATED_SKILLS_IN_JOB_FAIL';

export const FETCH_SKILL_START = 'FETCH_SKILL_START';
export const FETCH_SKILL_SUCCESS = 'FETCH_SKILL_SUCCESS';
export const FETCH_SKILL_FAIL = 'FETCH_SKILL_FAIL';

export const FETCH_RELATED_JOBS_IN_SKILL_START = 'FETCH_RELATED_JOBS_IN_SKILL_START';
export const FETCH_RELATED_JOBS_IN_SKILL_SUCCESS = 'FETCH_RELATED_JOBS_IN_SKILL_SUCCESS';
export const FETCH_RELATED_JOBS_IN_SKILL_FAIL = 'FETCH_RELATED_JOBS_IN_SKILL_FAIL';

export const FETCH_RELATED_SKILLS_IN_SKILL_START = 'FETCH_RELATED_SKILLS_IN_SKILL_START';
export const FETCH_RELATED_SKILLS_IN_SKILL_SUCCESS = 'FETCH_RELATED_SKILLS_IN_SKILL_SUCCESS';
export const FETCH_RELATED_SKILLS_IN_SKILL_FAIL = 'FETCH_RELATED_SKILLS_IN_SKILL_FAIL';

export const SET_QUERY_VALUE_SUCCESS = 'SET_QUERY_VALUE_SUCCESS';
export const SET_SEARCH_HISTORY_SUCCESS = 'SET_SEARCH_HISTORY_SUCCESS';
export const RE_SET_QUERY_JOBS_SUCCESS = 'RE_SET_QUERY_JOBS_SUCCESS';
export const FETCH_QUERY_JOBS_START = 'FETCH_QUERY_JOBS_START';
export const FETCH_QUERY_JOBS_SUCCESS = 'FETCH_QUERY_JOBS_SUCCESS';
export const FETCH_QUERY_JOBS_FAIL = 'FETCH_QUERY_JOBS_FAIL';

export const FETCH_AUTO_COMPLETE_JOBS_START = 'FETCH_AUTO_COMPLETE_JOBS_START';
export const FETCH_AUTO_COMPLETE_JOBS_SUCCESS = 'FETCH_AUTO_COMPLETE_JOBS_SUCCESS';
export const FETCH_AUTO_COMPLETE_JOBS_FAIL = 'FETCH_AUTO_COMPLETE_JOBS_FAIL';
export const RE_SET_AUTO_COMPLETE_JOBS_SUCCESS = 'RE_SET_AUTO_COMPLETE_JOBS_SUCCESS';